stages:
    - clean
    - build
    - run
    - check

fab cleanup:
    stage: clean
    tags:
        - gadi
    script:
        - ./lfric_atm-fab-clean.sh

fab build:
    stage: build
    tags:
        - gadi
    script:
        - ci-qsub ./lfric_atm-fab-build.sh
    timeout: 2 hours
    variables:
        NCPU: 16
    artifacts:
        paths:
            - job.log
            - lfric_core_revision
            - lfric_apps_revision

fab run:
    stage: run
    tags:
        - gadi
    script:
        - ci-qsub ./lfric_atm-fab-run.sh
    timeout: 2 hours
    variables:
        NCPU: 6
    artifacts:
        paths:
            - job.log

fab check:
    stage: check
    tags:
        - gadi
    script:
        - python3 ./lfric_atm-fab-check.py
