stages:
    - clean
    - build
    - run
    - check

fab cleanup:
    stage: clean
    tags:
        - gadi
    script:
        - ./lfric_atm-fab-clean.sh

fab build:
    stage: build
    tags:
        - gadi
    script:
        - ./lfric_atm-fab-build.sh
    timeout: 4 hours
    variables:
        NCPU: 1
    artifacts:
            - configuration.nml
        paths:
            - atm_ifort_1stage

fab run:
    stage: run
    tags:
        - gadi
    script:
        - ./lfric_atm-fab-run.sh
    timeout: 4 hours
    variables:
        NCPU: 4
    artifacts:
            - PET0.lfric_atm.Log

fab check:
    stage: check
    tags:
        - gadi
    script:
        - python3 ./lfric_atm-fab-check.py
