stages:
    - clean
    - lint
    - build
    - run
    - check

fab cleanup:
    stage: clean
    tags:
        - gadi
    script:
        - ./lfric_atm-fab-clean.sh

fab lint:
    stage: lint
    allow_failure: true
    tags:
        - gadi
    script:
        - python3 -m pip install --user pycodestyle
        - python3 -m pycodestyle ./fab_framework

fab build:
    stage: build
    tags:
        - gadi
    script:
        - ci-qsub ./lfric_atm-fab-build.sh
    timeout: 2 hours
    variables:
        NCPU: 16
        GIT_SUBMODULE_STRATEGY: recursive
    artifacts:
        paths:
            - lfric_core_revision
            - lfric_apps_revision

fab run:
    stage: run
    tags:
        - gadi
    script:
        - ci-qsub ./lfric_atm-fab-run.sh
    timeout: 2 hours
    variables:
        NCPU: 6
    artifacts:
        paths:
            - job.log

fab check:
    stage: check
    tags:
        - gadi
    script:
        - python3 ./lfric_atm-fab-check.py
