stages:
    - clean
    - build
    - run
    - check

fab cleanup:
    stage: clean
    tags:
        - gadi
    script:
        - ./lfric_atm-fab-clean.sh

fab build:
    stage: build
    tags:
        - gadi
    script:
        - ci-qsub ./lfric_atm-fab-build.sh
    timeout: 4 hours
    variables:
        NCPU: 1
    artifacts:
        paths:
            - /scratch/hc46/hc46_gitlab/builds/0/bom/ngm/lfric/lfric_atm-fab/example
            - /scratch/hc46/hc46_gitlab/builds/0/bom/ngm/lfric/lfric_atm-fab/metadata
            - /scratch/hc46/hc46_gitlab/builds/0/bom/ngm/lfric/lfric_atm-fab/lfric_atm.exe
            - /scratch/hc46/hc46_gitlab/builds/0/bom/ngm/lfric/lfric_atm-fab/lfric_revision

fab run:
    stage: run
    tags:
        - gadi
    script:
        - ./lfric_atm-fab-run.sh
    timeout: 4 hours
    variables:
        NCPU: 4
    artifacts:
        paths:
            - PET0.lfric_atm.Log

fab check:
    stage: check
    tags:
        - gadi
    script:
        - python3 ./lfric_atm-fab-check.py
