#!/bin/bash

#PBS -l ncpus=4
#PBS -l mem=16GB
#PBS -l jobfs=100MB
#PBS -q normal
#PBS -P hc46
#PBS -l walltime=4:00:00
#PBS -l storage=scratch/hc46
#PBS -W umask=0022
#PBS -l wd

BIN_DIR=/scratch/hc46/hc46_gitlab/builds/$CI_RUNNER_SHORT_TOKEN/0/bom/ngm/lfric/lfric_atm-fab/atm_ifort_1stage
echo $BIN_DIR

rev=$(rev < "lfric_revision")
echo $rev
#rev=46556
#echo $rev

CONFIG_DIR=/scratch/hc46/hc46_gitlab/builds/$CI_RUNNER_SHORT_TOKEN/0/bom/ngm/lfric/lfric_atm-fab/lfric_source_${rev}/source/lfric/lfric_atm/example/
echo $CONFIG_DIR

module use /scratch/hc46/hc46_gitlab/ngm/modules/
module load lfric-v0/intel-openmpi-lfric-fab

imagerun mpirun -np 4 ./lfric_atm.exe configuration.nml
